### PR TITLE
Added a Setup.bash

### PR DESCRIPTION
**Pull request by Keith-Khadar**
I added a setup.bash so we can start adding in aliases and to ``source /opt/ros/jazzy/setup.bash``

### CODE REVIEW

**Review by cbrxyz — APPROVED** [review]
Thanks keith!

**Comment by cbrxyz** [comment]
@Keith-Khadar Do you think it's fine if I change `MIL_REPO` to point to the root of the folder, instead of `src`? I don't think there's much advantage into teleporting into `src`, since you would have to go up one folder to access any github/script stuff.

**Comment by Keith-Khadar** [comment]
Yeah that sounds good to me

**Comment by cbrxyz** [comment]
grazie, done ([d011e80](https://github.com/uf-mil/mil2/commit/d011e8064c6955ab57850197e93f2f5b5df2e6cc))

**Pull request merged**
